'use strict';

window.fixtures = {};
window.fixtures.mixes = [{
url: 'https://www.mixcloud.com/greenleader/rec-sessions-541-dec-12-2012/',
djs: ['greenleader'],
title: 'REC Sessions #541',
date: 'Dec 12 2012',
},{
    url: 'https://www.mixcloud.com/greenleader/rec-sessions-714-green-leader-b2b-yennix/',
djs: ['greenleader','yennix'],
title: 'REC Sessions #714',
},{
url: 'https://www.mixcloud.com/greenleader/chicken-and-cake/',
djs: ['greenleader'],
title: 'chicken and cake',
},{
url: 'http://www.paulgrouchy.com/tofu/tofu-always_changin.mp3',
djs: ['tofu'],
title: 'always changin\'',
date: 'March 11th, 2015',
description: '40 mins of dnb',
size: 57,
},{
url: 'http://www.paulgrouchy.com/tofu/tofu-ddub_approved.mp3',
djs: ['tofu'],
title: 'ddub approved',
date: 'July 23rd, 2014',
description: '1.5 hrs of dnb',
size: 122,
},{
url: 'http://www.paulgrouchy.com/tofu/tofu-dr_idiot.mp3',
djs: ['tofu'],
title: 'dr. idiot',
date: 'June 18th, 2014',
description: '1.5 hrs of dnb',
size: 124,
},{
url: 'http://www.paulgrouchy.com/tofu/tofu-swingindnb.mp3',
djs: ['tofu'],
title: 'swingin\' dnb',
date: 'March 26th, 2014',
description: '36 mins of eleco swing followed by 25 mins of dnb',
size: 84,
},{
url: 'http://www.paulgrouchy.com/tofu/tofu-spring_bounce.mp3',
djs: ['tofu'],
title: 'spring bounce',
date: 'February 26th, 2014',
description: '46 mins of dnb',
size: 63,
},{
url: 'http://www.paulgrouchy.com/tofu/tofu-hittinThirty.mp3',
djs: ['tofu'],
title: 'hittin\' thirty',
date: 'March 20th, 2013',
description: '63 mins of dnb',
size: 86,
},{
url: 'http://www.paulgrouchy.com/tofu/greenleader_b2b_tofu-yinAndBang.mp3',
djs: ['greenleader', 'tofu'],
title: 'yin and bang',
date: 'February 27th, 2013',
description: '2 hrs of dnb, greenleader b2b tofu',
size: 163,
},
{
  url: 'http://intbass.com/archives/20130112-2113-Mr. Zodiac-LiVe from Belgium.mp3',
  djs: ['Mr. Zodiac'],
  title: 'LiVe from Belgium',
  date: '20130112',
},
{
  url: 'http://intbass.com/archives/20130210-2020-Mr. Zodiac-Funky Green Vibez.mp3',
  djs: ['Mr. Zodiac'],
  title: 'Funky Green Vibez 20130210',
  date: '20130210',
},
{
  url: 'http://intbass.com/archives/20130306-2109-AMS Crew tbone-The Chillout Sessions.mp3',
  djs: ['tbone', 'ams-crew'],
  title: 'The Chillout Sessions',
  date: '20130306',
},
{
  url: 'http://intbass.com/archives/20130308-2326-AdvisoryBone-The Collective Boner Sessions.mp3',
  djs: ['tbone', 'advisory'],
  title: 'The Collective Boner Sessions',
  date: '20130308',
},
{
  url: 'http://intbass.com/archives/20130310-1732-Mr. Zodiac-Funky Green Vibez.mp3',
  djs: ['Mr. Zodiac'],
  title: 'Funky Green Vibez 20130310',
  date: '20130310',
},
{
  url: 'http://intbass.com/archives/20130314-2239-tbone-Wheeeee sessions.mp3',
  djs: ['tbone'],
  title: 'Wheeeee sessions',
  date: '20130314',
},
{
  url: 'http://intbass.com/archives/20130329-2107-Mr. Zodiac-Funky Green Vibez.mp3',
  djs: ['Mr. Zodiac'],
  title: 'Funky Green Vibez 20130329',
  date: '20130329',
},
{
  url: 'http://intbass.com/archives/20130330-1943-Mr. Zodiac-Funky Green Vibez.mp3',
  djs: ['Mr. Zodiac'],
  title: 'Funky Green Vibez 20130330',
  date: '20130330',
},
{
  url: 'http://intbass.com/archives/20130404-1327-tbone and JSE-superfunhappyliquiddays!.mp3',
  djs: ['tbone', 'JSE'],
  title: 'superfunhappyliquiddays!',
  date: '20130404',
},
{
  url: 'http://intbass.com/archives/20130404-2007-Mr. Zodiac and JSE and jvn and tbone-3 Hour 4-way Special.mp3',
  djs: ['Mr. Zodiac','JSE','jvn','tbone'],
  title: '3 Hour 4-way Special',
  date: '20130404',
},
{
  url: 'http://intbass.com/archives/20130419-2357-Precision-Fresh Traxx Radio live from Whistler BC.mp3',
  djs: ['Precision'],
  title: 'Fresh Traxx Radio from Whistler BC',
  date: '20130419',
},
{
  url: 'http://intbass.com/archives/20130608-2226-Mr. Zodiac-Funky Green Vibez.mp3',
  djs: ['Mr. Zodiac'],
  title: 'Funky Green Vibez',
  date: '20130608',
},
{
  url: 'http://intbass.com/archives/badass-beats-february-23-2013.mp3',
  djs: ['anoshi'],
  title: 'badass beats february-23-2013',
  date: 'february-23-2013',
},
{
  url: 'http://intbass.com/archives/jvn_all_spectrasoul_mix_320.mp3',
  djs: ['fatso panda'],
  title: 'all spectrasoul mix',
},
{
  url: 'http://intbass.com/archives/jvn_hypertensive_encephalopathy.mp3',
  djs: ['fatso panda'],
  title: 'hypertensive encephalopathy',
},
{
  url: 'http://intbass.com/archives/jvn_one_day_with_rendic.mp3',
  djs: ['fatso panda'],
  title: 'one day with rendic',
},
{
  url: 'http://intbass.com/archives/jvn_polar_sessions_mid_summer_treats_2012.mp3',
  djs: ['fatso panda'],
  title: 'polar sessions mid summer treats 2012',
},
{
  url: 'http://intbass.com/archives/jvn_polar_sessions.mp3',
  djs: ['fatso panda'],
  title: 'polar sessions',
},
{
  url: 'http://intbass.com/archives/jvn_reverse_proxy_to_your_brain.mp3',
  djs: ['fatso panda'],
  title: 'reverse proxy to your brain',
},
{
  url: 'http://intbass.com/archives/jvn_welcome_summer.mp3',
  djs: ['fatso panda'],
  title: 'welcome summer',
},
{
  url: 'http://intbass.com/archives/jvn_winter_morning.mp3',
  djs: ['fatso panda'],
  title: 'winter morning',
},
{
  url: 'http://intbass.com/archives/REC0246.mp3',
  djs: ['toronto crew'],
  title: 'REC0246',
},
{
  url: 'http://intbass.com/archives/REC0545.mp3',
  djs: ['toronto crew'],
  title: 'REC0545',
},
{
  url: 'http://intbass.com/archives/REC0552.mp3',
  djs: ['toronto crew'],
  title: 'REC0552',
},
{
  url: 'http://intbass.com/archives/REC0573.mp3',
  djs: ['toronto crew'],
  title: 'REC0573',
},
{
  url: 'http://intbass.com/archives/REC0577.mp3',
  djs: ['toronto crew'],
  title: 'REC0577',
},
{
  url: 'http://intbass.com/archives/REC0581.mp3',
  djs: ['toronto crew'],
  title: 'REC0581',
},
{
  url: 'http://intbass.com/archives/REC0582.mp3',
  djs: ['toronto crew'],
  title: 'REC0582',
},
{
  url: 'http://intbass.com/archives/REC0583.mp3',
  djs: ['toronto crew'],
  title: 'REC0583',
},
{
  url: 'http://intbass.com/archives/REC0594.mp3',
  djs: ['toronto crew'],
  title: 'REC0594',
},
{
  url: 'http://intbass.com/archives/REC0651.mp3',
  djs: ['toronto crew'],
  title: 'REC0651',
},
{
  url: 'http://intbass.com/archives/REC0653.mp3',
  djs: ['toronto crew'],
  title: 'REC0653',
},
{
  url: 'http://intbass.com/archives/REC0672_ed.mp3',
  djs: ['toronto crew'],
  title: 'REC0672_ed',
},
{
  url: 'http://intbass.com/archives/REC0677.mp3',
  djs: ['toronto crew'],
  title: 'REC0677',
},
{
  url: 'http://intbass.com/archives/REC0679.mp3',
  djs: ['toronto crew'],
  title: 'REC0679',
},
{
  url: 'http://intbass.com/archives/20121231-1652-jvn-Polar Session NYE jam live by jvn.mp3',
  djs: ['fatso panda'],
  title: 'Polar Session NYE jam live',
  date: '20121231',
},
{
  url: 'http://intbass.com/archives/20130104-2001-Mr. Zodiac & tbone-Impromptu Sessions live from BELGIUM.mp3',
  djs: ['Mr Zodiac', 'tbone'],
  title: 'Impromptu Sessions live from BELGIUM',
  date: '20130104',
},
{
  url: 'http://intbass.com/archives/20130121-1647-tbone-Snowcovered.mp3',
  djs: ['tbone'],
  title: 'Snowcovered',
  date: '20130121',
},
{
  url: 'http://intbass.com/archives/Anoshi-BADASS BEATS-2012_12_29.mp3',
  djs: ['anoshi'],
  title: 'BADASS BEATS 2012_12_29',
  date: '2012_12_29',
},
{
  url: 'http://intbass.com/archives/BADASS_BEATS_2013_01_19.mp3',
  djs: ['anoshi'],
  title: 'BADASS_BEATS_2013_01_19',
  date: '2013_01_19',
},
{
  url: 'http://intbass.com/archives/FNB0239.mp3',
  djs: ['tbone'],
  title: 'FNB0239',
},
{
  url: 'http://intbass.com/archives/JVN0114.mp3',
  djs: ['fatso panda'],
  title: 'JVN0114',
},
{
  url: 'http://intbass.com/archives/jvn_polarsessions_xmas.mp3',
  djs: ['fatso panda'],
  title: 'polarsessions xmas',
},
{
  url: 'http://intbass.com/archives/REC0175.mp3',
  djs: ['toronto crew'],
  title: 'REC0175',
},
{
  url: 'http://intbass.com/archives/REC0197.mp3',
  djs: ['toronto crew'],
  title: 'REC0197',
},
{
  url: 'http://intbass.com/archives/REC0232.mp3',
  djs: ['toronto crew'],
  title: 'REC0232',
},
{
  url: 'http://intbass.com/archives/REC0256.mp3',
  djs: ['toronto crew'],
  title: 'REC0256',
},
{
  url: 'http://intbass.com/archives/REC0273.mp3',
  djs: ['toronto crew'],
  title: 'REC0273',
},
{
  url: 'http://intbass.com/archives/REC0293.mp3',
  djs: ['toronto crew'],
  title: 'REC0293',
},
{
  url: 'http://intbass.com/archives/REC0294.mp3',
  djs: ['toronto crew'],
  title: 'REC0294',
},
{
  url: 'http://intbass.com/archives/REC0303.mp3',
  djs: ['toronto crew'],
  title: 'REC0303',
},
{
  url: 'http://intbass.com/archives/REC0320.mp3',
  djs: ['toronto crew'],
  title: 'REC0320',
},
{
  url: 'http://intbass.com/archives/REC0322.mp3',
  djs: ['toronto crew'],
  title: 'REC0322',
},
{
  url: 'http://intbass.com/archives/REC0327.mp3',
  djs: ['toronto crew'],
  title: 'REC0327',
},
{
  url: 'http://intbass.com/archives/REC0486.mp3',
  djs: ['toronto crew'],
  title: 'REC0486',
},
{
  url: 'http://intbass.com/archives/REC0366.mp3',
  djs: ['ddub', 'greenleader'],
  title: 'atop an anthenian ascent',
},
{
  url: 'http://intbass.com/archives/REC0497.mp3',
  djs: ['toronto crew'],
  title: 'REC0497',
},
{
  url: 'http://intbass.com/archives/REC0510.mp3',
  djs: ['toronto crew'],
  title: 'REC0510',
}];
